/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Shailesh
 */
public class ConsigneeDetails extends javax.swing.JDialog {

    /**
     * Creates new form ConsigneeDetails
     */

    private SelectConsignee sc;
    private String conName;
    private String conAddress;
    private String conGSTNo;

    public String getConName() {
        return conName;
    }

    public String getConAddress() {
        return conAddress;
    }

    public String getConGSTNo() {
        return conGSTNo;
    }
    
    public ConsigneeDetails(java.awt.Frame parent, boolean modal, SelectConsignee sc) {
        super(parent, modal);
        initComponents();
        this.sc = sc;
        setLocationRelativeTo(null);
    }

    
    void setConsigneeDetails(String name, String address, String GSTNo) {
        txtConName.setText(name);
        txtConAdd.setText(address);
        txtConGST.setText(GSTNo);
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consigneesInformationPanel = new javax.swing.JPanel();
        lblConName = new javax.swing.JLabel();
        txtConName = new javax.swing.JTextField();
        lblConAdd = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtConAdd = new javax.swing.JTextArea();
        lblConGST = new javax.swing.JLabel();
        txtConGST = new javax.swing.JTextField();
        btnSelectCustomer = new javax.swing.JButton();
        btnSelectCustomer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        consigneesInformationPanel.setBackground(new java.awt.Color(25, 25, 35));
        consigneesInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consignee's Details", 2, 0, new java.awt.Font("Century Gothic", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        consigneesInformationPanel.setPreferredSize(new java.awt.Dimension(412, 491));

        lblConName.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblConName.setForeground(new java.awt.Color(255, 255, 255));
        lblConName.setText("Name : ");

        txtConName.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        lblConAdd.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblConAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblConAdd.setText("Address");

        txtConAdd.setColumns(20);
        txtConAdd.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtConAdd.setRows(5);
        jScrollPane6.setViewportView(txtConAdd);

        lblConGST.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblConGST.setForeground(new java.awt.Color(255, 255, 255));
        lblConGST.setText("GST No:");

        txtConGST.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        btnSelectCustomer.setBackground(new java.awt.Color(0, 0, 0));
        btnSelectCustomer.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnSelectCustomer.setText("Save");
        btnSelectCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCustomerActionPerformed(evt);
            }
        });

        btnSelectCustomer1.setBackground(new java.awt.Color(0, 0, 0));
        btnSelectCustomer1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnSelectCustomer1.setText("Select Consignee");
        btnSelectCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCustomer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consigneesInformationPanelLayout = new javax.swing.GroupLayout(consigneesInformationPanel);
        consigneesInformationPanel.setLayout(consigneesInformationPanelLayout);
        consigneesInformationPanelLayout.setHorizontalGroup(
            consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consigneesInformationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consigneesInformationPanelLayout.createSequentialGroup()
                        .addComponent(lblConAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consigneesInformationPanelLayout.createSequentialGroup()
                        .addComponent(lblConName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtConName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consigneesInformationPanelLayout.createSequentialGroup()
                        .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConGST, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(consigneesInformationPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnSelectCustomer)))
                        .addGap(18, 18, 18)
                        .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consigneesInformationPanelLayout.createSequentialGroup()
                                .addComponent(btnSelectCustomer1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtConGST))))
                .addGap(100, 100, 100))
        );
        consigneesInformationPanelLayout.setVerticalGroup(
            consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consigneesInformationPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConName)
                    .addComponent(lblConName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConAdd))
                .addGap(35, 35, 35)
                .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConGST)
                    .addComponent(lblConGST, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(consigneesInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(consigneesInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(consigneesInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCustomerActionPerformed
        conName = txtConName.getText();
        conAddress = txtConAdd.getText();
        conGSTNo = txtConGST.getText();
        this.dispose();
    }//GEN-LAST:event_btnSelectCustomerActionPerformed

    private void btnSelectCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCustomer1ActionPerformed
        this.dispose();
        sc.setVisible(true);
    }//GEN-LAST:event_btnSelectCustomer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectCustomer;
    private javax.swing.JButton btnSelectCustomer1;
    private javax.swing.JPanel consigneesInformationPanel;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblConAdd;
    private javax.swing.JLabel lblConGST;
    private javax.swing.JLabel lblConName;
    private javax.swing.JTextArea txtConAdd;
    private javax.swing.JTextField txtConGST;
    private javax.swing.JTextField txtConName;
    // End of variables declaration//GEN-END:variables

}
