package ui;


import database.CustomerTable;
import database.DatabaseManagement;
import database.InvoiceTable;
import invoice.Invoice;
import invoice.InvoiceDetails;
import invoice.Product;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import net.proteanit.sql.DbUtils;
import update.UpdateSoftware;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shailesh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private SelectCustomer sc = null;
    private boolean isConsigneeSameAsBuyer;
    public MainFrame() {
        initComponents();
        isConsigneeSameAsBuyer = true;
        sc = new SelectCustomer(this);
        products = new ArrayList<>();
        jdcDate.setDate(new Date());
        txtInvoiceNo.setText("MMC-"+Invoice.getNextInvoiceNo());
        updateTableData();
            dlm = (DefaultListModel)productList.getModel();
////        btnAdd.setEnabled(true);
//        btnDelete.setEnabled(false);
//        btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabs = new javax.swing.JTabbedPane();
        customerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int x,int y){
                return false;
            }
        };
        detailsPanel = new javax.swing.JPanel();
        txtGSTNo = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblGSTNo = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        operationPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        invoicePanel = new javax.swing.JPanel();
        buyersInformationPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAdd = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        lblGST = new javax.swing.JLabel();
        txtGST = new javax.swing.JTextField();
        btnSelectCustomer = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        buyersInformationPanel1 = new javax.swing.JPanel();
        lblInvoiceNo = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JTextField();
        txtTransportMode = new javax.swing.JTextField();
        lblTransportMode = new javax.swing.JLabel();
        txtTermsOfPayment = new javax.swing.JTextField();
        lblTermsOfPayment = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblVehicleNo = new javax.swing.JLabel();
        txtVehicleNo = new javax.swing.JTextField();
        jdcDate = new com.toedter.calendar.JDateChooser();
        buyersInformationPanel2 = new javax.swing.JPanel();
        lblGoods = new javax.swing.JLabel();
        lblHSN = new javax.swing.JLabel();
        txtHSN = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblRate = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        lblPer = new javax.swing.JLabel();
        txtPer = new javax.swing.JTextField();
        txtGoods = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList<>();
        btnDeleteProduct = new javax.swing.JButton();
        SGSTRate = new javax.swing.JTextField();
        lblIGSTRate = new javax.swing.JTextField();
        lblCGSTRate = new javax.swing.JTextField();
        lblGSTRate = new javax.swing.JLabel();
        lblSGSTRate = new javax.swing.JTextField();
        CGSTRate = new javax.swing.JTextField();
        IGSTRate = new javax.swing.JTextField();
        btnCreateInvoice = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        updateMenu = new javax.swing.JMenu();
        checkForUpdate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTabs.setToolTipText("");
        mainTabs.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N

        customerPanel.setBackground(new java.awt.Color(255, 255, 255));

        customerTable.setBackground(new java.awt.Color(6, 1, 30));
        customerTable.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        customerTable.setForeground(new java.awt.Color(255, 250, 255));
        customerTable.setFillsViewportHeight(true);
        customerTable.setGridColor(new java.awt.Color(15, 163, 177));
        customerTable.setRowHeight(30);
        customerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        customerTable.getTableHeader().setResizingAllowed(false);
        customerTable.getTableHeader().setReorderingAllowed(false);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        detailsPanel.setBackground(new java.awt.Color(255, 250, 255));

        txtGSTNo.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        lblCustomerName.setText("Customer Name : ");

        txtCustomerName.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N

        lblGSTNo.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        lblGSTNo.setText("GST No. :");

        lblAddress.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        lblAddress.setText("Address :");

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        operationPanel.setBackground(new java.awt.Color(255, 250, 255));

        btnAdd.setBackground(new java.awt.Color(30, 27, 24));
        btnAdd.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(15, 163, 177));
        btnAdd.setText("Add");
        btnAdd.setContentAreaFilled(false);
        btnAdd.setOpaque(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(30, 27, 24));
        btnUpdate.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(15, 163, 177));
        btnUpdate.setText("Update");
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setOpaque(true);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(30, 27, 24));
        btnDelete.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(15, 163, 177));
        btnDelete.setText("Delete");
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(30, 27, 24));
        btnClear.setFont(new java.awt.Font("Copse", 1, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(15, 163, 177));
        btnClear.setText("Clear");
        btnClear.setContentAreaFilled(false);
        btnClear.setOpaque(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationPanelLayout = new javax.swing.GroupLayout(operationPanel);
        operationPanel.setLayout(operationPanelLayout);
        operationPanelLayout.setHorizontalGroup(
            operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(operationPanelLayout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(operationPanelLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        operationPanelLayout.setVerticalGroup(
            operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(operationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addComponent(lblGSTNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCustomerName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailsPanelLayout.createSequentialGroup()
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(operationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );

        mainTabs.addTab("Customers", new javax.swing.ImageIcon(getClass().getResource("/images/support.png")), customerPanel, "Manage Your Customers"); // NOI18N
        customerPanel.getAccessibleContext().setAccessibleName("");

        invoicePanel.setBackground(new java.awt.Color(255, 255, 255));
        invoicePanel.setPreferredSize(new java.awt.Dimension(1524, 880));

        buyersInformationPanel.setBackground(new java.awt.Color(85, 91, 110));
        buyersInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buyer's Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N

        lblName.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name : ");

        txtName.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        lblAdd.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("Address");

        txtAdd.setColumns(20);
        txtAdd.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtAdd.setRows(5);
        jScrollPane3.setViewportView(txtAdd);

        lblGST.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblGST.setForeground(new java.awt.Color(255, 255, 255));
        lblGST.setText("GST No:");

        txtGST.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        btnSelectCustomer.setBackground(new java.awt.Color(0, 0, 0));
        btnSelectCustomer.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnSelectCustomer.setText("Select Customer");
        btnSelectCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCustomerActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Consignee same as Buyer");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buyersInformationPanelLayout = new javax.swing.GroupLayout(buyersInformationPanel);
        buyersInformationPanel.setLayout(buyersInformationPanelLayout);
        buyersInformationPanelLayout.setHorizontalGroup(
            buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyersInformationPanelLayout.createSequentialGroup()
                .addGroup(buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyersInformationPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(buyersInformationPanelLayout.createSequentialGroup()
                                .addComponent(lblGST, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGST))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buyersInformationPanelLayout.createSequentialGroup()
                                .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buyersInformationPanelLayout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(buyersInformationPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnSelectCustomer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buyersInformationPanelLayout.setVerticalGroup(
            buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyersInformationPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdd))
                .addGap(35, 35, 35)
                .addGroup(buyersInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGST)
                    .addComponent(lblGST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jCheckBox1)
                .addGap(35, 35, 35)
                .addComponent(btnSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buyersInformationPanel1.setBackground(new java.awt.Color(25, 25, 35));
        buyersInformationPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N

        lblInvoiceNo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblInvoiceNo.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoiceNo.setText("Invoice No :");

        txtInvoiceNo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtInvoiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceNoActionPerformed(evt);
            }
        });

        txtTransportMode.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtTransportMode.setText("Road");

        lblTransportMode.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblTransportMode.setForeground(new java.awt.Color(255, 255, 255));
        lblTransportMode.setText("Mode Of Transport :");

        txtTermsOfPayment.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtTermsOfPayment.setText("RTGS");

        lblTermsOfPayment.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblTermsOfPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblTermsOfPayment.setText("Term Payment : ");

        lblDate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date : ");

        lblVehicleNo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblVehicleNo.setForeground(new java.awt.Color(255, 255, 255));
        lblVehicleNo.setText("Vehicle No :");

        txtVehicleNo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        jdcDate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        javax.swing.GroupLayout buyersInformationPanel1Layout = new javax.swing.GroupLayout(buyersInformationPanel1);
        buyersInformationPanel1.setLayout(buyersInformationPanel1Layout);
        buyersInformationPanel1Layout.setHorizontalGroup(
            buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyersInformationPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(buyersInformationPanel1Layout.createSequentialGroup()
                        .addComponent(lblVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVehicleNo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyersInformationPanel1Layout.createSequentialGroup()
                        .addComponent(lblTermsOfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTermsOfPayment))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyersInformationPanel1Layout.createSequentialGroup()
                        .addComponent(lblTransportMode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTransportMode))
                    .addGroup(buyersInformationPanel1Layout.createSequentialGroup()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyersInformationPanel1Layout.createSequentialGroup()
                        .addComponent(lblInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buyersInformationPanel1Layout.setVerticalGroup(
            buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyersInformationPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInvoiceNo)
                    .addComponent(lblInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addGap(35, 35, 35)
                .addGroup(buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTransportMode)
                    .addComponent(lblTransportMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTermsOfPayment)
                    .addComponent(lblTermsOfPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(buyersInformationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVehicleNo)
                    .addComponent(lblVehicleNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buyersInformationPanel2.setBackground(new java.awt.Color(85, 91, 110));
        buyersInformationPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 20), new java.awt.Color(255, 255, 255))); // NOI18N

        lblGoods.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblGoods.setForeground(new java.awt.Color(255, 255, 255));
        lblGoods.setText("Goods : ");

        lblHSN.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblHSN.setForeground(new java.awt.Color(255, 255, 255));
        lblHSN.setText("HSN/SAC :");

        txtHSN.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        lblQuantity.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity : ");

        txtQuantity.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        lblRate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblRate.setForeground(new java.awt.Color(255, 255, 255));
        lblRate.setText("Rate :");

        txtRate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        lblPer.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblPer.setForeground(new java.awt.Color(255, 255, 255));
        lblPer.setText("Per : ");

        txtPer.setEditable(false);
        txtPer.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        txtPer.setText("KG");

        txtGoods.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        btnAddProduct.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnAddProduct.setText("+ Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        productList.setModel(new DefaultListModel());
        productList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(productList);

        btnDeleteProduct.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnDeleteProduct.setText("Delete");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        SGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        SGSTRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SGSTRate.setText("9");
        SGSTRate.setPreferredSize(new java.awt.Dimension(24, 27));

        lblIGSTRate.setEditable(false);
        lblIGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lblIGSTRate.setForeground(new java.awt.Color(255, 255, 255));
        lblIGSTRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblIGSTRate.setText("IGST");
        lblIGSTRate.setBorder(null);
        lblIGSTRate.setOpaque(false);
        lblIGSTRate.setPreferredSize(new java.awt.Dimension(24, 27));

        lblCGSTRate.setEditable(false);
        lblCGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lblCGSTRate.setForeground(new java.awt.Color(255, 255, 255));
        lblCGSTRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblCGSTRate.setText("CGST");
        lblCGSTRate.setBorder(null);
        lblCGSTRate.setOpaque(false);
        lblCGSTRate.setPreferredSize(new java.awt.Dimension(24, 27));

        lblGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblGSTRate.setForeground(new java.awt.Color(255, 255, 255));
        lblGSTRate.setText("GST Rate :");

        lblSGSTRate.setEditable(false);
        lblSGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lblSGSTRate.setForeground(new java.awt.Color(255, 255, 255));
        lblSGSTRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblSGSTRate.setText("SGST");
        lblSGSTRate.setBorder(null);
        lblSGSTRate.setOpaque(false);

        CGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        CGSTRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CGSTRate.setText("9");
        CGSTRate.setPreferredSize(new java.awt.Dimension(24, 27));

        IGSTRate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        IGSTRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IGSTRate.setText("0");
        IGSTRate.setPreferredSize(new java.awt.Dimension(24, 27));

        javax.swing.GroupLayout buyersInformationPanel2Layout = new javax.swing.GroupLayout(buyersInformationPanel2);
        buyersInformationPanel2.setLayout(buyersInformationPanel2Layout);
        buyersInformationPanel2Layout.setHorizontalGroup(
            buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                                .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buyersInformationPanel2Layout.createSequentialGroup()
                                    .addComponent(lblPer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPer))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buyersInformationPanel2Layout.createSequentialGroup()
                                    .addComponent(lblRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                                .addComponent(lblHSN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHSN, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                    .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buyersInformationPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buyersInformationPanel2Layout.setVerticalGroup(
            buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyersInformationPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGoods)
                    .addComponent(lblGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(SGSTRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGSTRate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHSN)
                    .addComponent(lblHSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQuantity)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRate)
                    .addComponent(lblRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPer)
                    .addComponent(lblPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(buyersInformationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );

        btnCreateInvoice.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateInvoice.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCreateInvoice.setText("Create Invoice");
        btnCreateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateInvoice)
                    .addGroup(invoicePanelLayout.createSequentialGroup()
                        .addComponent(buyersInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(buyersInformationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(buyersInformationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buyersInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyersInformationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyersInformationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateInvoice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabs.addTab("Invoice", new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png")), invoicePanel); // NOI18N

        updateMenu.setText("Update");

        checkForUpdate.setText("Check For Update");
        checkForUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkForUpdateActionPerformed(evt);
            }
        });
        updateMenu.add(checkForUpdate);

        jMenuBar1.add(updateMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1294, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        mainTabs.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void clearFields() {
        txtCustomerName.setText("");
        txtGSTNo.setText("");
        txtAddress.setText("");
        updateTableData();
    }
    private boolean isAnyFieldEmpty(){
        return (txtCustomerName.getText().trim().equals("") 
                && getAppendedText(txtAddress).trim().equals("") 
                && txtGSTNo.getText().trim().equals(""));
    }
    private void updateTableData() {
        ResultSet rs = null;
        try {
            rs = DatabaseManagement.select("customer", null, "customername", "address","gstno");
            customerTable.setModel(DbUtils.resultSetToTableModel(rs));
            sc.customerTable.setModel(customerTable.getModel());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Issue :  " + e);
        } finally {
            try {
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Problem in closing rs or preparedStatement :  " + e);
            }
        }
    }
    private void addInDatabase(){
        if(!CustomerTable.isCustomerExist(txtGSTNo.getText())){
            if(!isAnyFieldEmpty()){
                CustomerTable.insert(txtCustomerName.getText().trim(),getAppendedText(txtAddress),txtGSTNo.getText());
                JOptionPane.showMessageDialog(null, "Record added successfully");
                clearFields();
                updateTableData();
            }
            else
                JOptionPane.showMessageDialog(null, "Please re-check the fields!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Customer already exists!");
        }
    }
    private void updateInDatabase(){
//        btnAdd.setEnabled(false);
        if(!isAnyFieldEmpty()){
            
            CustomerTable.update(getCustomerId(),txtCustomerName.getText(), getAppendedText(txtAddress), txtGSTNo.getText());
            clearFields();
            updateTableData();
        }
//        btnAdd.setEnabled(true);
    }
    private void deleteFromDatabase(){
        if(customerTable.getSelectedRow()!=-1){
            CustomerTable.delete(getCustomerId());
            updateTableData();
        }
    }
    private String getAppendedText(JTextArea ta){
        return ta.getText().replace("\n", " ");
    }
    public int getCustomerId(){
        int selectedRow = customerTable.getSelectedRow();
        int customerId = 0;
        if(selectedRow != -1){
            String gstno = (String)customerTable.getValueAt(selectedRow, 2);
            customerId = CustomerTable.getCustomerId(gstno);
        }
        return customerId;
    }
    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        int selectedRow = customerTable.getSelectedRow();
        if(selectedRow!=-1){
            txtCustomerName.setText((String)customerTable.getValueAt(selectedRow, 0));
            txtAddress.setText((String)customerTable.getValueAt(selectedRow, 1));
            txtGSTNo.setText((String)customerTable.getValueAt(selectedRow, 2));
        }
    }//GEN-LAST:event_customerTableMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addInDatabase();
//        btnAdd.setEnabled(false);
//        btnUpdate.setEnabled(false);
//        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!isAnyFieldEmpty()){
            updateInDatabase();
        }
        else{
            JOptionPane.showMessageDialog(null, "Field(s) cannot be Empty or have spaces, Please Recheck");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteFromDatabase();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
//        btnAdd.setEnabled(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSelectCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCustomerActionPerformed
        sc.setVisible(true);
    }//GEN-LAST:event_btnSelectCustomerActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try {
            String productName = txtGoods.getText().trim();
            String hsn = txtHSN.getText().trim();
            int sgst = Integer.parseInt(SGSTRate.getText().trim());
            int cgst = Integer.parseInt(CGSTRate.getText().trim());
            int igst = Integer.parseInt(IGSTRate.getText().trim());
            double quantity = Double.parseDouble(txtQuantity.getText().trim());
            double price = Double.parseDouble(txtRate.getText().trim());
            String per = txtPer.getText();
            products.add(new Product(productName, hsn, quantity, price, per));
            String pro = productName + " ," + hsn + " ," + cgst + " ," +sgst + " ," + igst + " ," + quantity + " ," + price + " ," + per;
            dlm = (DefaultListModel) productList.getModel();
            dlm.addElement(pro);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check details properly in product details");
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        int selectedIndex = productList.getSelectedIndex();
        if(selectedIndex != -1){
            try {
                products.remove(selectedIndex);
                dlm.remove(selectedIndex);
            System.out.println(products + "in +del");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Please check details properly in product details");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a product to delete");
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed
    private void clearAllFields(){
        txtName.setText("");
        txtGST.setText("");
        txtAdd.setText("");
       
        txtVehicleNo.setText("");
        
        txtGoods.setText("");
        txtHSN.setText("");
        txtQuantity.setText("");
        txtRate.setText("");
    }
    
    void setCustomerDetails(String name, String address, String GSTNo) {
            txtName.setText(name);
            txtAdd.setText(address);
            txtGST.setText(GSTNo);
    }
    private void btnCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInvoiceActionPerformed
        if(!CustomerTable.isCustomerExist(txtGST.getText())){
            if(!(txtName.getText().trim().equals("")
                && getAppendedText(txtAdd).trim().equals("") 
                && txtGST.getText().trim().equals(""))){
                
                CustomerTable.insert(txtName.getText(), getAppendedText(txtAdd), txtGST.getText());
                updateTableData();
            }
        }
        try {
            Invoice invoice = new Invoice(System.getProperty("user.home") + "\\Documents\\invoices", Double.parseDouble(CGSTRate.getText()), Double.parseDouble(SGSTRate.getText()), Double.parseDouble(IGSTRate.getText()));
            invoice.writeCustomerDetails(txtName.getText().trim(), getAppendedText(txtAdd), txtGST.getText().trim());
            if(isConsigneeSameAsBuyer){
                invoice.writeConsigneeDetails(txtName.getText().trim(), getAppendedText(txtAdd), txtGST.getText().trim());
            }
            invoice.writeInvoiceDetails(new InvoiceDetails(txtInvoiceNo.getText(),DateFormat.getDateInstance(DateFormat.MEDIUM).format(jdcDate.getDate()), txtTransportMode.getText().trim(), txtTermsOfPayment.getText().trim()));
            invoice.writeVehicleDetails(txtVehicleNo.getText().trim());
            invoice.writeProductDetails(products);
            InvoiceTable.insert(txtName.getText().trim(), (int)invoice.getTotalPriceIncludingGST());
            invoice.saveAndClose();
            JOptionPane.showMessageDialog(null, "Sucessfully invoice created, Check your documents!");
            clearAllFields();
            dlm.removeAllElements();
            products.removeAll(products);
            txtInvoiceNo.setText("MMC-"+Invoice.getNextInvoiceNo());
            Thread.sleep(2000);
            if(Desktop.isDesktopSupported()){
                Desktop.getDesktop().open(new File(invoice.getAbsolutePath()));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Something went wrong " + e);
        }
        
    }//GEN-LAST:event_btnCreateInvoiceActionPerformed

    private void txtInvoiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceNoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        isConsigneeSameAsBuyer = !isConsigneeSameAsBuyer;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void checkForUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkForUpdateActionPerformed
        try {
            if(UpdateSoftware.isUpdateAvailable()){
                UpdateSoftware.install();
            }
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_checkForUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CGSTRate;
    private javax.swing.JTextField IGSTRate;
    private javax.swing.JTextField SGSTRate;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateInvoice;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnSelectCustomer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel buyersInformationPanel;
    private javax.swing.JPanel buyersInformationPanel1;
    private javax.swing.JPanel buyersInformationPanel2;
    private javax.swing.JMenuItem checkForUpdate;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser jdcDate;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JTextField lblCGSTRate;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGST;
    private javax.swing.JLabel lblGSTNo;
    private javax.swing.JLabel lblGSTRate;
    private javax.swing.JLabel lblGoods;
    private javax.swing.JLabel lblHSN;
    private javax.swing.JTextField lblIGSTRate;
    private javax.swing.JLabel lblInvoiceNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPer;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblRate;
    private javax.swing.JTextField lblSGSTRate;
    private javax.swing.JLabel lblTermsOfPayment;
    private javax.swing.JLabel lblTransportMode;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JTabbedPane mainTabs;
    private javax.swing.JPanel operationPanel;
    private javax.swing.JList<String> productList;
    private javax.swing.JTextArea txtAdd;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtGST;
    private javax.swing.JTextField txtGSTNo;
    private javax.swing.JTextField txtGoods;
    private javax.swing.JTextField txtHSN;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtTermsOfPayment;
    private javax.swing.JTextField txtTransportMode;
    private javax.swing.JTextField txtVehicleNo;
    private javax.swing.JMenu updateMenu;
    // End of variables declaration//GEN-END:variables
    private List<Product> products;
    private DefaultListModel dlm;
}
